// Lesson system — 20 lessons, 4 units
export const UNITS = [
  { id: 1, titleEs: '¿Qué es el dinero?', titleEn: 'What is money?', color: '#F59E0B', lessonIds: [1,2,3,4,5] },
  { id: 2, titleEs: 'Aprender a ahorrar', titleEn: 'Learning to save', color: '#14B8A6', lessonIds: [6,7,8,9,10] },
  { id: 3, titleEs: 'Decisiones inteligentes', titleEn: 'Smart decisions', color: '#3B82F6', lessonIds: [11,12,13,14,15] },
  { id: 4, titleEs: 'Metas y sueños', titleEn: 'Goals and dreams', color: '#A855F7', lessonIds: [16,17,18,19,20] },
]

export const LESSONS = [
  // ─── UNIT 1: ¿Qué es el dinero? ───────────────────────────────────
  {
    id: 1,
    unit: 1,
    scenario: 'piggy',
    titleEs: '¿Qué es el dinero?',
    titleEn: 'What is money?',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L1Q1',
        scenario: 'piggy',
        text: { es: '¿Qué es una moneda?', en: 'What is a coin?' },
        options: [
          { id: 'A', text: { es: 'Dinero de metal', en: 'Metal money' } },
          { id: 'B', text: { es: 'Un juguete', en: 'A toy' } },
          { id: 'C', text: { es: 'Un dulce', en: 'A candy' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L1Q2',
        scenario: 'piggy',
        text: { es: '¿Para qué usamos el dinero?', en: 'What do we use money for?' },
        options: [
          { id: 'A', text: { es: 'Para jugar', en: 'To play' } },
          { id: 'B', text: { es: 'Para comprar cosas', en: 'To buy things' } },
          { id: 'C', text: { es: 'Para comer', en: 'To eat it' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L1Q3',
        scenario: 'jar',
        text: { es: '¿Cuáles son formas de dinero?', en: 'Which are forms of money?' },
        options: [
          { id: 'A', text: { es: 'Monedas y billetes', en: 'Coins and bills' } },
          { id: 'B', text: { es: 'Piedras y palos', en: 'Rocks and sticks' } },
          { id: 'C', text: { es: 'Hojas y flores', en: 'Leaves and flowers' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 2,
    unit: 1,
    scenario: 'jar',
    titleEs: '¿De dónde viene el dinero?',
    titleEn: 'Where does money come from?',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L2Q1',
        scenario: 'jar',
        text: { es: '¿De dónde viene el dinero que usan los adultos?', en: 'Where does adult money come from?' },
        options: [
          { id: 'A', text: { es: 'De los árboles', en: 'From trees' } },
          { id: 'B', text: { es: 'Del trabajo', en: 'From working' } },
          { id: 'C', text: { es: 'Del cielo', en: 'From the sky' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L2Q2',
        scenario: 'piggy',
        text: { es: '¿Cómo pueden ganar dinero los niños?', en: 'How can kids earn money?' },
        options: [
          { id: 'A', text: { es: 'Ayudando en casa', en: 'Helping at home' } },
          { id: 'B', text: { es: 'Durmiendo', en: 'Sleeping' } },
          { id: 'C', text: { es: 'Viendo televisión', en: 'Watching TV' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L2Q3',
        scenario: 'choice',
        text: { es: 'Tu abuela te da $5 por tu cumpleaños. ¿Qué tipo de dinero es?', en: 'Your grandma gives you $5 for your birthday. What kind of money is this?' },
        options: [
          { id: 'A', text: { es: 'Dinero robado', en: 'Stolen money' } },
          { id: 'B', text: { es: 'Un regalo', en: 'A gift' } },
          { id: 'C', text: { es: 'Dinero falso', en: 'Fake money' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 3,
    unit: 1,
    scenario: 'choice',
    titleEs: 'Necesidades y deseos',
    titleEn: 'Needs and wants',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L3Q1',
        scenario: 'choice',
        text: { es: '¿Cuál es una NECESIDAD?', en: 'Which one is a NEED?' },
        options: [
          { id: 'A', text: { es: 'Un juguete nuevo', en: 'A new toy' } },
          { id: 'B', text: { es: 'Comida para comer', en: 'Food to eat' } },
          { id: 'C', text: { es: 'Helado de fresa', en: 'Strawberry ice cream' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L3Q2',
        scenario: 'jar',
        text: { es: '¿Cuál es un DESEO?', en: 'Which one is a WANT?' },
        options: [
          { id: 'A', text: { es: 'Zapatos para ir a la escuela', en: 'Shoes for school' } },
          { id: 'B', text: { es: 'Una galleta de chocolate', en: 'A chocolate cookie' } },
          { id: 'C', text: { es: 'Agua para beber', en: 'Water to drink' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L3Q3',
        scenario: 'piggy',
        text: { es: '¿Por qué es importante saber la diferencia entre necesidad y deseo?', en: 'Why is it important to know the difference between a need and a want?' },
        options: [
          { id: 'A', text: { es: 'Para gastar bien el dinero', en: 'To spend money wisely' } },
          { id: 'B', text: { es: 'Para tener más juguetes', en: 'To get more toys' } },
          { id: 'C', text: { es: 'Para ir de vacaciones', en: 'To go on vacation' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 4,
    unit: 1,
    scenario: 'piggy',
    titleEs: 'El precio de las cosas',
    titleEn: 'The price of things',
    coinReward: 8,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L4Q1',
        scenario: 'piggy',
        text: { es: '¿Qué es el precio?', en: 'What is a price?' },
        options: [
          { id: 'A', text: { es: 'El color de algo', en: 'The color of something' } },
          { id: 'B', text: { es: 'El nombre de algo', en: 'The name of something' } },
          { id: 'C', text: { es: 'Cuánto cuesta algo', en: 'How much something costs' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
      {
        id: 'L4Q2',
        scenario: 'choice',
        text: { es: 'Un libro cuesta $10. ¿Tienes suficiente con $7?', en: 'A book costs $10. Do you have enough with $7?' },
        options: [
          { id: 'A', text: { es: 'Sí, me sobra', en: 'Yes, with change' } },
          { id: 'B', text: { es: 'Exacto', en: 'Exactly right' } },
          { id: 'C', text: { es: 'No, me faltan $3', en: 'No, I need $3 more' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
      {
        id: 'L4Q3',
        scenario: 'jar',
        text: { es: 'Tienes $12 y el juguete cuesta $9. ¿Cuánto te sobra?', en: 'You have $12 and the toy costs $9. How much is left?' },
        options: [
          { id: 'A', text: { es: '$3', en: '$3' } },
          { id: 'B', text: { es: '$2', en: '$2' } },
          { id: 'C', text: { es: '$4', en: '$4' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 5,
    unit: 1,
    scenario: 'choice',
    titleEs: '¡Reto de unidad 1!',
    titleEn: 'Unit 1 Challenge!',
    coinReward: 15,
    isUnitChallenge: true,
    unlocksBuilding: 'house',
    questions: [
      {
        id: 'L5Q1',
        scenario: 'piggy',
        text: { es: '¿Qué es el dinero?', en: 'What is money?' },
        options: [
          { id: 'A', text: { es: 'Algo que usamos para comprar cosas', en: 'Something we use to buy things' } },
          { id: 'B', text: { es: 'Un tipo de juego', en: 'A type of game' } },
          { id: 'C', text: { es: 'Solo lo tienen los adultos', en: 'Only adults have it' } },
        ],
        correct: 'A',
        coinsIfCorrect: 3,
      },
      {
        id: 'L5Q2',
        scenario: 'jar',
        text: { es: '¿Qué es una necesidad?', en: 'What is a need?' },
        options: [
          { id: 'A', text: { es: 'Algo que queremos mucho', en: 'Something we want a lot' } },
          { id: 'B', text: { es: 'Algo que necesitamos para vivir', en: 'Something we need to live' } },
          { id: 'C', text: { es: 'Un regalo especial', en: 'A special gift' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L5Q3',
        scenario: 'choice',
        text: { es: 'Tienes $5. El dulce cuesta $3. ¿Cuánto te sobra?', en: 'You have $5. Candy costs $3. How much is left?' },
        options: [
          { id: 'A', text: { es: '$3', en: '$3' } },
          { id: 'B', text: { es: '$1', en: '$1' } },
          { id: 'C', text: { es: '$2', en: '$2' } },
        ],
        correct: 'C',
        coinsIfCorrect: 3,
      },
      {
        id: 'L5Q4',
        scenario: 'piggy',
        text: { es: '¿De dónde viene el dinero?', en: 'Where does money come from?' },
        options: [
          { id: 'A', text: { es: 'De trabajar y ganar', en: 'From working and earning' } },
          { id: 'B', text: { es: 'De los sueños', en: 'From dreams' } },
          { id: 'C', text: { es: 'Del supermercado', en: 'From the supermarket' } },
        ],
        correct: 'A',
        coinsIfCorrect: 3,
      },
      {
        id: 'L5Q5',
        scenario: 'jar',
        text: { es: '¿Un helado es una necesidad o un deseo?', en: 'Is ice cream a need or a want?' },
        options: [
          { id: 'A', text: { es: 'Necesidad', en: 'A need' } },
          { id: 'B', text: { es: 'Los dos', en: 'Both' } },
          { id: 'C', text: { es: 'Un deseo', en: 'A want' } },
        ],
        correct: 'C',
        coinsIfCorrect: 3,
      },
    ],
  },

  // ─── UNIT 2: Aprender a ahorrar ──────────────────────────────────
  {
    id: 6,
    unit: 2,
    scenario: 'jar',
    titleEs: '¿Qué es ahorrar?',
    titleEn: 'What is saving?',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L6Q1',
        scenario: 'jar',
        text: { es: '¿Qué significa ahorrar?', en: 'What does saving mean?' },
        options: [
          { id: 'A', text: { es: 'Gastar rápido', en: 'Spending fast' } },
          { id: 'B', text: { es: 'Regalar el dinero', en: 'Giving money away' } },
          { id: 'C', text: { es: 'Guardar dinero para después', en: 'Keeping money for later' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
      {
        id: 'L6Q2',
        scenario: 'piggy',
        text: { es: '¿Dónde puedes guardar tus ahorros?', en: 'Where can you keep your savings?' },
        options: [
          { id: 'A', text: { es: 'En el piso', en: 'On the floor' } },
          { id: 'B', text: { es: 'En una alcancía', en: 'In a piggy bank' } },
          { id: 'C', text: { es: 'En el jardín', en: 'In the garden' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L6Q3',
        scenario: 'choice',
        text: { es: '¿Para qué sirve ahorrar?', en: 'What is saving good for?' },
        options: [
          { id: 'A', text: { es: 'Para comprar algo especial después', en: 'To buy something special later' } },
          { id: 'B', text: { es: 'Para perder el dinero', en: 'To lose the money' } },
          { id: 'C', text: { es: 'Para dárselo a los extraños', en: 'To give it to strangers' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 7,
    unit: 2,
    scenario: 'piggy',
    titleEs: 'La alcancía mágica',
    titleEn: 'The magic piggy bank',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L7Q1',
        scenario: 'piggy',
        text: { es: 'Tienes 10 monedas. Ahorras 4. ¿Cuántas te quedan para gastar?', en: 'You have 10 coins. You save 4. How many can you spend?' },
        options: [
          { id: 'A', text: { es: '4', en: '4' } },
          { id: 'B', text: { es: '6', en: '6' } },
          { id: 'C', text: { es: '8', en: '8' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L7Q2',
        scenario: 'jar',
        text: { es: '¿Qué pasa si ahorras un poco cada día?', en: 'What happens if you save a little each day?' },
        options: [
          { id: 'A', text: { es: 'Nunca tendrás suficiente', en: "You'll never have enough" } },
          { id: 'B', text: { es: 'Juntas mucho dinero con el tiempo', en: 'You collect a lot of money over time' } },
          { id: 'C', text: { es: 'El dinero desaparece', en: 'The money disappears' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L7Q3',
        scenario: 'choice',
        text: { es: 'Recibes $2 cada semana. Después de 5 semanas, ¿cuánto tienes si no gastas nada?', en: 'You get $2 each week. After 5 weeks, how much do you have if you spend nothing?' },
        options: [
          { id: 'A', text: { es: '$7', en: '$7' } },
          { id: 'B', text: { es: '$5', en: '$5' } },
          { id: 'C', text: { es: '$10', en: '$10' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 8,
    unit: 2,
    scenario: 'jar',
    titleEs: 'Pequeños ahorros, grandes sueños',
    titleEn: 'Small savings, big dreams',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L8Q1',
        scenario: 'jar',
        text: { es: 'Tu meta es $15. Tienes $8. ¿Cuánto más necesitas?', en: 'Your goal is $15. You have $8. How much more do you need?' },
        options: [
          { id: 'A', text: { es: '$8', en: '$8' } },
          { id: 'B', text: { es: '$7', en: '$7' } },
          { id: 'C', text: { es: '$6', en: '$6' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L8Q2',
        scenario: 'piggy',
        text: { es: '¿Qué te ayuda a ahorrar más fácil?', en: 'What helps you save more easily?' },
        options: [
          { id: 'A', text: { es: 'Gastar todo cuando llega', en: 'Spending all when it arrives' } },
          { id: 'B', text: { es: 'Tener una meta clara', en: 'Having a clear goal' } },
          { id: 'C', text: { es: 'Comprar muchos dulces', en: 'Buying lots of candy' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L8Q3',
        scenario: 'choice',
        text: { es: '¿Cuál es la mejor forma de ahorrar?', en: 'What is the best way to save?' },
        options: [
          { id: 'A', text: { es: 'Guardar un poco cada vez que recibes dinero', en: 'Save a little every time you get money' } },
          { id: 'B', text: { es: 'Solo ahorrar cuando te sobra', en: 'Only save what is left over' } },
          { id: 'C', text: { es: 'Esperar a tener mucho para guardar', en: 'Wait until you have a lot to save' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 9,
    unit: 2,
    scenario: 'choice',
    titleEs: 'Gastar o ahorrar',
    titleEn: 'Spend or save',
    coinReward: 8,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L9Q1',
        scenario: 'choice',
        text: { es: 'Ves un juguete genial pero tu meta es comprar un libro. ¿Qué haces?', en: 'You see a cool toy but your goal is to buy a book. What do you do?' },
        options: [
          { id: 'A', text: { es: 'Compro el juguete porque quiero', en: 'Buy the toy because I want it' } },
          { id: 'B', text: { es: 'Sigo ahorrando para mi meta', en: 'Keep saving for my goal' } },
          { id: 'C', text: { es: 'Pido prestado', en: 'Borrow money' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L9Q2',
        scenario: 'piggy',
        text: { es: '¿Qué pasa si gastas todo antes de llegar a tu meta?', en: 'What happens if you spend everything before reaching your goal?' },
        options: [
          { id: 'A', text: { es: 'Tienes que empezar de nuevo', en: 'You have to start over' } },
          { id: 'B', text: { es: 'La meta se cumple sola', en: 'The goal completes itself' } },
          { id: 'C', text: { es: 'Nada, el dinero vuelve', en: 'Nothing, the money comes back' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L9Q3',
        scenario: 'jar',
        text: { es: '¿Cuándo es bueno gastar el dinero?', en: 'When is it good to spend money?' },
        options: [
          { id: 'A', text: { es: 'Cuando compras cosas que realmente necesitas o quieres de verdad', en: 'When buying things you truly need or really want' } },
          { id: 'B', text: { es: 'Cuando tienes ganas de gastar', en: 'When you feel like spending' } },
          { id: 'C', text: { es: 'Siempre que tengas dinero', en: 'Whenever you have money' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 10,
    unit: 2,
    scenario: 'piggy',
    titleEs: '¡Reto de unidad 2!',
    titleEn: 'Unit 2 Challenge!',
    coinReward: 15,
    isUnitChallenge: true,
    unlocksBuilding: 'park',
    questions: [
      {
        id: 'L10Q1',
        scenario: 'jar',
        text: { es: '¿Qué significa ahorrar?', en: 'What does saving mean?' },
        options: [
          { id: 'A', text: { es: 'Guardar dinero para un objetivo', en: 'Keeping money for a goal' } },
          { id: 'B', text: { es: 'Gastar todo rápido', en: 'Spending everything fast' } },
          { id: 'C', text: { es: 'Esconder el dinero', en: 'Hiding the money' } },
        ],
        correct: 'A',
        coinsIfCorrect: 3,
      },
      {
        id: 'L10Q2',
        scenario: 'piggy',
        text: { es: 'Tienes $20. Ahorras $8. ¿Cuánto puedes gastar?', en: 'You have $20. You save $8. How much can you spend?' },
        options: [
          { id: 'A', text: { es: '$10', en: '$10' } },
          { id: 'B', text: { es: '$12', en: '$12' } },
          { id: 'C', text: { es: '$8', en: '$8' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L10Q3',
        scenario: 'choice',
        text: { es: '¿Qué te ayuda a cumplir una meta de ahorro?', en: 'What helps you reach a savings goal?' },
        options: [
          { id: 'A', text: { es: 'Gastar en cada oportunidad', en: 'Spending every chance you get' } },
          { id: 'B', text: { es: 'Guardar un poco cada vez', en: 'Saving a little at a time' } },
          { id: 'C', text: { es: 'Pedir dinero prestado', en: 'Borrowing money' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L10Q4',
        scenario: 'jar',
        text: { es: 'Tu meta es $12. Tienes $5. Ahorras $3 más. ¿Cuánto te falta?', en: 'Your goal is $12. You have $5. You save $3 more. How much is left?' },
        options: [
          { id: 'A', text: { es: '$4', en: '$4' } },
          { id: 'B', text: { es: '$5', en: '$5' } },
          { id: 'C', text: { es: '$3', en: '$3' } },
        ],
        correct: 'A',
        coinsIfCorrect: 3,
      },
      {
        id: 'L10Q5',
        scenario: 'piggy',
        text: { es: '¿Por qué es mejor ahorrar antes de gastar?', en: 'Why is it better to save before spending?' },
        options: [
          { id: 'A', text: { es: 'Para tener dinero para lo importante', en: 'To have money for what matters' } },
          { id: 'B', text: { es: 'Para parecer rico', en: 'To look rich' } },
          { id: 'C', text: { es: 'Porque los adultos lo dicen', en: 'Because adults say so' } },
        ],
        correct: 'A',
        coinsIfCorrect: 3,
      },
    ],
  },

  // ─── UNIT 3: Decisiones inteligentes ─────────────────────────────
  {
    id: 11,
    unit: 3,
    scenario: 'choice',
    titleEs: 'Pensar antes de comprar',
    titleEn: 'Think before you buy',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L11Q1',
        scenario: 'choice',
        text: { es: '¿Qué debes preguntarte antes de gastar?', en: 'What should you ask yourself before spending?' },
        options: [
          { id: 'A', text: { es: '¿Lo necesito o solo lo quiero?', en: 'Do I need it or just want it?' } },
          { id: 'B', text: { es: '¿Qué color tiene?', en: 'What color is it?' } },
          { id: 'C', text: { es: '¿Es grande?', en: 'Is it big?' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L11Q2',
        scenario: 'piggy',
        text: { es: 'Quieres dos juguetes pero solo tienes dinero para uno. ¿Qué haces?', en: 'You want two toys but only have money for one. What do you do?' },
        options: [
          { id: 'A', text: { es: 'Lloro hasta conseguirlos', en: 'Cry until I get them' } },
          { id: 'B', text: { es: 'Elijo el que más me gusta', en: 'Choose the one I like most' } },
          { id: 'C', text: { es: 'Los tomo los dos', en: 'Take both' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L11Q3',
        scenario: 'jar',
        text: { es: '¿Qué es tomar una buena decisión con el dinero?', en: 'What is making a good money decision?' },
        options: [
          { id: 'A', text: { es: 'Gastar sin pensar', en: 'Spending without thinking' } },
          { id: 'B', text: { es: 'Pensar si vale la pena antes de gastar', en: 'Thinking if it is worth it before spending' } },
          { id: 'C', text: { es: 'Pedir más a tus padres', en: 'Asking parents for more' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 12,
    unit: 3,
    scenario: 'jar',
    titleEs: 'Comparar precios',
    titleEn: 'Comparing prices',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L12Q1',
        scenario: 'jar',
        text: { es: 'La tienda A vende manzanas por $2. La tienda B por $3. ¿Cuál es mejor?', en: 'Store A sells apples for $2. Store B for $3. Which is better?' },
        options: [
          { id: 'A', text: { es: 'La tienda B porque es más cara', en: 'Store B because it is more expensive' } },
          { id: 'B', text: { es: 'La tienda A porque es más barata', en: 'Store A because it is cheaper' } },
          { id: 'C', text: { es: 'Las dos son iguales', en: 'Both are the same' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L12Q2',
        scenario: 'choice',
        text: { es: '¿Por qué es bueno comparar precios?', en: 'Why is it good to compare prices?' },
        options: [
          { id: 'A', text: { es: 'Para gastar menos y ahorrar más', en: 'To spend less and save more' } },
          { id: 'B', text: { es: 'Para comprar lo más caro', en: 'To buy the most expensive' } },
          { id: 'C', text: { es: 'Para ir a más tiendas', en: 'To visit more stores' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L12Q3',
        scenario: 'piggy',
        text: { es: '¿Qué significa que algo está "en oferta"?', en: 'What does it mean something is "on sale"?' },
        options: [
          { id: 'A', text: { es: 'Que cuesta más de normal', en: 'It costs more than usual' } },
          { id: 'B', text: { es: 'Que cuesta menos de normal', en: 'It costs less than usual' } },
          { id: 'C', text: { es: 'Que es de mejor calidad', en: 'It is better quality' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 13,
    unit: 3,
    scenario: 'piggy',
    titleEs: 'Dinero prestado',
    titleEn: 'Borrowed money',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L13Q1',
        scenario: 'piggy',
        text: { es: '¿Qué pasa cuando pides prestado dinero?', en: 'What happens when you borrow money?' },
        options: [
          { id: 'A', text: { es: 'Te lo regalan', en: 'They give it to you' } },
          { id: 'B', text: { es: 'Tienes que devolverlo', en: 'You have to give it back' } },
          { id: 'C', text: { es: 'Lo puedes guardar para siempre', en: 'You can keep it forever' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L13Q2',
        scenario: 'jar',
        text: { es: 'Tu amigo te presta $4. ¿Qué debes hacer?', en: 'Your friend lends you $4. What should you do?' },
        options: [
          { id: 'A', text: { es: 'Gastarlo todo', en: 'Spend it all' } },
          { id: 'B', text: { es: 'Olvidarlo', en: 'Forget about it' } },
          { id: 'C', text: { es: 'Devolverlo cuando puedas', en: 'Pay it back when you can' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
      {
        id: 'L13Q3',
        scenario: 'choice',
        text: { es: '¿Por qué no es buena idea pedir prestado siempre?', en: 'Why is it not good to always borrow?' },
        options: [
          { id: 'A', text: { es: 'Porque tienes que devolver y te quedas sin dinero', en: 'Because you repay and have less money' } },
          { id: 'B', text: { es: 'Porque es muy fácil', en: 'Because it is too easy' } },
          { id: 'C', text: { es: 'Porque el banco no quiere', en: 'Because the bank does not want it' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 14,
    unit: 3,
    scenario: 'choice',
    titleEs: 'Presupuesto básico',
    titleEn: 'Basic budget',
    coinReward: 8,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L14Q1',
        scenario: 'choice',
        text: { es: '¿Qué es un presupuesto?', en: 'What is a budget?' },
        options: [
          { id: 'A', text: { es: 'Un plan de cuánto gastar y cuánto ahorrar', en: 'A plan for how much to spend and save' } },
          { id: 'B', text: { es: 'Un tipo de juguete', en: 'A type of toy' } },
          { id: 'C', text: { es: 'Una lista de deseos', en: 'A wish list' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L14Q2',
        scenario: 'jar',
        text: { es: 'Tienes $10 esta semana. ¿Cuál es un buen plan?', en: 'You have $10 this week. Which is a good plan?' },
        options: [
          { id: 'A', text: { es: 'Gastar $8 y ahorrar $2', en: 'Spend $8 and save $2' } },
          { id: 'B', text: { es: 'Gastar todo en un día', en: 'Spend everything in one day' } },
          { id: 'C', text: { es: 'Ahorrar todo sin gastar nada', en: 'Save everything without spending' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L14Q3',
        scenario: 'piggy',
        text: { es: '¿Por qué es útil tener un plan de dinero?', en: 'Why is it useful to have a money plan?' },
        options: [
          { id: 'A', text: { es: 'Para saber siempre cuánto tienes', en: 'To always know how much you have' } },
          { id: 'B', text: { es: 'Para no pensar en el dinero', en: 'To not think about money' } },
          { id: 'C', text: { es: 'Para gastar más rápido', en: 'To spend faster' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 15,
    unit: 3,
    scenario: 'jar',
    titleEs: '¡Reto de unidad 3!',
    titleEn: 'Unit 3 Challenge!',
    coinReward: 15,
    isUnitChallenge: true,
    unlocksBuilding: 'school',
    questions: [
      {
        id: 'L15Q1',
        scenario: 'choice',
        text: { es: '¿Cuánto cuesta más: $5 o $8?', en: 'Which costs more: $5 or $8?' },
        options: [
          { id: 'A', text: { es: '$5', en: '$5' } },
          { id: 'B', text: { es: 'Los dos igual', en: 'Both the same' } },
          { id: 'C', text: { es: '$8', en: '$8' } },
        ],
        correct: 'C',
        coinsIfCorrect: 3,
      },
      {
        id: 'L15Q2',
        scenario: 'piggy',
        text: { es: '¿Qué debes hacer antes de comprar algo?', en: 'What should you do before buying something?' },
        options: [
          { id: 'A', text: { es: 'Correr a la tienda', en: 'Run to the store' } },
          { id: 'B', text: { es: 'Pensar si lo necesitas y si tienes suficiente', en: 'Think if you need it and if you have enough' } },
          { id: 'C', text: { es: 'Pedir más dinero', en: 'Ask for more money' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L15Q3',
        scenario: 'jar',
        text: { es: 'Si debes dinero, ¿qué es lo correcto?', en: 'If you owe money, what is the right thing to do?' },
        options: [
          { id: 'A', text: { es: 'Olvidarlo', en: 'Forget it' } },
          { id: 'B', text: { es: 'Devolverlo', en: 'Pay it back' } },
          { id: 'C', text: { es: 'Pedir más prestado', en: 'Borrow more' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L15Q4',
        scenario: 'choice',
        text: { es: 'Tienes $15. Quieres dos cosas: una de $6 y una de $11. ¿Puedes comprar las dos?', en: 'You have $15. You want two things: one $6 and one $11. Can you buy both?' },
        options: [
          { id: 'A', text: { es: 'Sí, con $2 de sobra', en: 'Yes, with $2 extra' } },
          { id: 'B', text: { es: 'No, cuesta $17 en total', en: 'No, it costs $17 total' } },
          { id: 'C', text: { es: 'Sí, exactamente', en: 'Yes, exactly' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
      {
        id: 'L15Q5',
        scenario: 'piggy',
        text: { es: '¿Qué es un presupuesto?', en: 'What is a budget?' },
        options: [
          { id: 'A', text: { es: 'Una lista de lo que quieres comprar', en: 'A list of things you want to buy' } },
          { id: 'B', text: { es: 'Un plan de cuánto gastar y ahorrar', en: 'A plan for how much to spend and save' } },
          { id: 'C', text: { es: 'El precio de las cosas', en: 'The price of things' } },
        ],
        correct: 'B',
        coinsIfCorrect: 3,
      },
    ],
  },

  // ─── UNIT 4: Metas y sueños ───────────────────────────────────────
  {
    id: 16,
    unit: 4,
    scenario: 'choice',
    titleEs: 'Establecer metas',
    titleEn: 'Setting goals',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L16Q1',
        scenario: 'choice',
        text: { es: '¿Qué es una meta?', en: 'What is a goal?' },
        options: [
          { id: 'A', text: { es: 'Algo que quieres lograr', en: 'Something you want to achieve' } },
          { id: 'B', text: { es: 'Un tipo de juego', en: 'A type of game' } },
          { id: 'C', text: { es: 'Una sorpresa', en: 'A surprise' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L16Q2',
        scenario: 'jar',
        text: { es: '¿Cuál es una buena meta de ahorro?', en: 'Which is a good saving goal?' },
        options: [
          { id: 'A', text: { es: 'Gastar todo lo antes posible', en: 'Spend everything as fast as possible' } },
          { id: 'B', text: { es: 'Ahorrar para una bicicleta nueva', en: 'Save for a new bicycle' } },
          { id: 'C', text: { es: 'Nunca ahorrar nada', en: 'Never save anything' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L16Q3',
        scenario: 'piggy',
        text: { es: '¿Qué necesitas para alcanzar una meta?', en: 'What do you need to reach a goal?' },
        options: [
          { id: 'A', text: { es: 'Suerte', en: 'Luck' } },
          { id: 'B', text: { es: 'Un plan y paciencia', en: 'A plan and patience' } },
          { id: 'C', text: { es: 'Mucho dinero de una vez', en: 'A lot of money at once' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 17,
    unit: 4,
    scenario: 'piggy',
    titleEs: 'Planear para el futuro',
    titleEn: 'Planning for the future',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L17Q1',
        scenario: 'piggy',
        text: { es: '¿Por qué es importante pensar en el futuro?', en: 'Why is it important to think about the future?' },
        options: [
          { id: 'A', text: { es: 'Para prepararse y tener lo que necesitas', en: 'To be prepared and have what you need' } },
          { id: 'B', text: { es: 'Porque el futuro da miedo', en: 'Because the future is scary' } },
          { id: 'C', text: { es: 'Para no disfrutar el presente', en: 'To not enjoy the present' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L17Q2',
        scenario: 'choice',
        text: { es: 'Quieres comprar algo que cuesta $20 en 4 semanas. ¿Cuánto debes ahorrar por semana?', en: 'You want to buy something for $20 in 4 weeks. How much should you save per week?' },
        options: [
          { id: 'A', text: { es: '$4', en: '$4' } },
          { id: 'B', text: { es: '$5', en: '$5' } },
          { id: 'C', text: { es: '$6', en: '$6' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L17Q3',
        scenario: 'jar',
        text: { es: '¿Cómo puedes rastrear tu progreso hacia una meta?', en: 'How can you track your progress toward a goal?' },
        options: [
          { id: 'A', text: { es: 'Adivinar cuánto tienes', en: 'Guess how much you have' } },
          { id: 'B', text: { es: 'Contar tu dinero regularmente', en: 'Count your money regularly' } },
          { id: 'C', text: { es: 'Preguntarle a alguien más', en: 'Ask someone else' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 18,
    unit: 4,
    scenario: 'jar',
    titleEs: 'Dar y compartir',
    titleEn: 'Giving and sharing',
    coinReward: 5,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L18Q1',
        scenario: 'jar',
        text: { es: '¿Por qué es bueno compartir?', en: 'Why is sharing good?' },
        options: [
          { id: 'A', text: { es: 'Ayuda a otros y te hace sentir bien', en: 'It helps others and makes you feel good' } },
          { id: 'B', text: { es: 'Porque pierdes todo', en: 'Because you lose everything' } },
          { id: 'C', text: { es: 'Para no tener que comprar más', en: 'So you do not have to buy more' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L18Q2',
        scenario: 'piggy',
        text: { es: 'Tienes $10. Decides dar $2 a tu amigo que los necesita. ¿Cuánto te queda?', en: 'You have $10. You decide to give $2 to a friend who needs it. How much do you have left?' },
        options: [
          { id: 'A', text: { es: '$9', en: '$9' } },
          { id: 'B', text: { es: '$7', en: '$7' } },
          { id: 'C', text: { es: '$8', en: '$8' } },
        ],
        correct: 'C',
        coinsIfCorrect: 2,
      },
      {
        id: 'L18Q3',
        scenario: 'choice',
        text: { es: '¿Qué puedes hacer con el dinero además de gastar y ahorrar?', en: 'What can you do with money besides spending and saving?' },
        options: [
          { id: 'A', text: { es: 'Esconderlo bajo la cama', en: 'Hide it under the bed' } },
          { id: 'B', text: { es: 'Donarlo a quienes lo necesitan', en: 'Donate it to those who need it' } },
          { id: 'C', text: { es: 'Quemarlo', en: 'Burn it' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 19,
    unit: 4,
    scenario: 'choice',
    titleEs: 'Dinero y felicidad',
    titleEn: 'Money and happiness',
    coinReward: 8,
    isUnitChallenge: false,
    unlocksBuilding: null,
    questions: [
      {
        id: 'L19Q1',
        scenario: 'choice',
        text: { es: '¿Puede el dinero comprar la felicidad?', en: 'Can money buy happiness?' },
        options: [
          { id: 'A', text: { es: 'Sí, siempre', en: 'Yes, always' } },
          { id: 'B', text: { es: 'No, pero ayuda a cubrir necesidades', en: 'No, but it helps meet needs' } },
          { id: 'C', text: { es: 'No importa el dinero', en: 'Money does not matter' } },
        ],
        correct: 'B',
        coinsIfCorrect: 2,
      },
      {
        id: 'L19Q2',
        scenario: 'piggy',
        text: { es: '¿Qué cosas importantes no se pueden comprar con dinero?', en: 'What important things cannot be bought with money?' },
        options: [
          { id: 'A', text: { es: 'La amistad y el amor', en: 'Friendship and love' } },
          { id: 'B', text: { es: 'Libros y juguetes', en: 'Books and toys' } },
          { id: 'C', text: { es: 'Comida y ropa', en: 'Food and clothing' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
      {
        id: 'L19Q3',
        scenario: 'jar',
        text: { es: '¿Para qué sirve aprender sobre el dinero?', en: 'What is the point of learning about money?' },
        options: [
          { id: 'A', text: { es: 'Para tomar mejores decisiones en la vida', en: 'To make better decisions in life' } },
          { id: 'B', text: { es: 'Para hacerse rico rápido', en: 'To get rich fast' } },
          { id: 'C', text: { es: 'Para no trabajar nunca', en: 'To never have to work' } },
        ],
        correct: 'A',
        coinsIfCorrect: 2,
      },
    ],
  },
  {
    id: 20,
    unit: 4,
    scenario: 'choice',
    titleEs: '¡Gran reto final!',
    titleEn: 'Big final challenge!',
    coinReward: 50,
    isUnitChallenge: true,
    unlocksBuilding: 'castle',
    questions: [
      {
        id: 'L20Q1',
        scenario: 'piggy',
        text: { es: '¿Qué es el dinero?', en: 'What is money?' },
        options: [
          { id: 'A', text: { es: 'Algo para intercambiar por bienes y servicios', en: 'Something exchanged for goods and services' } },
          { id: 'B', text: { es: 'Solo monedas doradas', en: 'Only golden coins' } },
          { id: 'C', text: { es: 'Una forma de jugar', en: 'A way to play' } },
        ],
        correct: 'A',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q2',
        scenario: 'jar',
        text: { es: '¿Qué es una necesidad?', en: 'What is a need?' },
        options: [
          { id: 'A', text: { es: 'Un juguete favorito', en: 'A favorite toy' } },
          { id: 'B', text: { es: 'Algo esencial para vivir', en: 'Something essential to live' } },
          { id: 'C', text: { es: 'Un viaje de vacaciones', en: 'A vacation trip' } },
        ],
        correct: 'B',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q3',
        scenario: 'choice',
        text: { es: 'Tienes $30. Gastas $12 y ahorras $8. ¿Cuánto te queda libre?', en: 'You have $30. You spend $12 and save $8. How much is left freely?' },
        options: [
          { id: 'A', text: { es: '$10', en: '$10' } },
          { id: 'B', text: { es: '$8', en: '$8' } },
          { id: 'C', text: { es: '$12', en: '$12' } },
        ],
        correct: 'A',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q4',
        scenario: 'piggy',
        text: { es: '¿Por qué es útil ahorrar antes de gastar?', en: 'Why is it useful to save before spending?' },
        options: [
          { id: 'A', text: { es: 'Para tener para lo importante', en: 'To have money for what matters' } },
          { id: 'B', text: { es: 'Porque ahorrar es aburrido', en: 'Because saving is boring' } },
          { id: 'C', text: { es: 'Para impresionar a los amigos', en: 'To impress friends' } },
        ],
        correct: 'A',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q5',
        scenario: 'jar',
        text: { es: '¿Cuál es la diferencia entre gastar y ahorrar?', en: 'What is the difference between spending and saving?' },
        options: [
          { id: 'A', text: { es: 'No hay diferencia', en: 'There is no difference' } },
          { id: 'B', text: { es: 'Gastar usa el dinero ahora; ahorrar lo guarda para después', en: 'Spending uses money now; saving keeps it for later' } },
          { id: 'C', text: { es: 'Ahorrar es perder el dinero', en: 'Saving is losing money' } },
        ],
        correct: 'B',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q6',
        scenario: 'choice',
        text: { es: 'Tu meta es $24. Ahorras $6 por semana. ¿En cuántas semanas llegas?', en: 'Your goal is $24. You save $6 per week. How many weeks to reach it?' },
        options: [
          { id: 'A', text: { es: '3 semanas', en: '3 weeks' } },
          { id: 'B', text: { es: '5 semanas', en: '5 weeks' } },
          { id: 'C', text: { es: '4 semanas', en: '4 weeks' } },
        ],
        correct: 'C',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q7',
        scenario: 'piggy',
        text: { es: '¿Qué debes hacer antes de pedir dinero prestado?', en: 'What should you do before borrowing money?' },
        options: [
          { id: 'A', text: { es: 'Pensar cómo lo vas a devolver', en: 'Think about how you will pay it back' } },
          { id: 'B', text: { es: 'Pedir tanto como puedas', en: 'Ask for as much as you can' } },
          { id: 'C', text: { es: 'Olvidarte de que lo pediste', en: 'Forget that you asked' } },
        ],
        correct: 'A',
        coinsIfCorrect: 6,
      },
      {
        id: 'L20Q8',
        scenario: 'jar',
        text: { es: '¿Cuál es el mejor consejo sobre el dinero?', en: 'What is the best money advice?' },
        options: [
          { id: 'A', text: { es: 'Gastar todo siempre', en: 'Always spend everything' } },
          { id: 'B', text: { es: 'Nunca gastar nada', en: 'Never spend anything' } },
          { id: 'C', text: { es: 'Ahorrar un poco, gastar con cuidado y dar cuando puedas', en: 'Save a little, spend carefully, and give when you can' } },
        ],
        correct: 'C',
        coinsIfCorrect: 6,
      },
    ],
  },
]

// backward compatibility
export const QUESTIONS = LESSONS
